#!/usr/bin/env bash
# Bash script that will display information about subdomains

sub_info () {
    
    if [ "$#" -eq 2 ]; then
        dig www.$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {printf "The subdomain www is a %s record and points to %s\n", $4, $5}'
    elif [ "$#" -eq 1 ]; then
        dig www.$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {printf "The subdomain www is a %s record and points to %s\n", $4, $5}'
        dig lb-01.$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {printf "The subdomain lb-01 is a %s record and points to %s\n", $4, $5}'
        dig web-01.$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {printf "The subdomain web-01 is a %s record and points to %s\n", $4, $5}'
        dig web-02.$1 | grep -A1 'ANSWER SECTION:' | awk '/IN/ {printf "The subdomain web-02 is a %s record and points to %s\n", $4, $5}'
    fi

}

sub_info $1 $2
