#!/usr/bin/env bash
# Script to install a load balancer.
sudo apt-get update
sudo apt-get -y install haproxy
sudo echo "
listen firstbalance
    bind *:80
    balance roundrobin
    server 4597-web-01 54.160.177.42:80 check
    server 4597-web-02 54.196.42.165:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
