#!/usr/bin/env bash
# Bash script thatthat gives you information about the school file.

for i in {1..100}
do
    if [ $(( i % 3)) == "0" ] && [ $(( i % 5)) == "0" ]
    then
        echo "FizzBuzz"
        continue
    elif [ $(( i % 3)) == "0" ]
    then
        echo "Fizz"
        continue
    elif [ $(( i % 5)) == "0" ]
    then
        echo "Buzz"
        continue
    fi
    echo "$i"
done