#!/usr/bin/env bash
# Displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi
contador=9
while [ $contador -ge 0 ]
do
  echo "Best School"
  if [[ "$contador" == '1' ]]
  then
    echo "Hi"
  fi
  ((contador--))
done