#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays three phrases
contador=1
while [ $contador -le 10 ]
do
  if [[ "$contador" == '4' ]]
  then
    echo "bad luck"
    ((contador++))
    continue

  elif [[ "$contador" == '8' ]]
  then
    echo "good luck"
    ((contador++))
    continue

  else
  echo "Best School"
  ((contador++))
  fi
done