#!/usr/bin/env bash
# This script display bad luck and good luck

i=0


while [ "$i" -lt 10 ]; do
	echo "Best School"
	i=$(("$i" + 1))
	if [ "$i" = 4 ] 
    then
		echo 'bad luck'
	elif [ "$i" = 8 ] 
    then 
        echo 'good luck'
	else
        echo "Best School"
    fi
done