#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and displays three phrases
contador=1
while [ $contador -le 20 ]
do
  echo "$contador"
  case $contador in
  4) echo "bad luck from China";;
  9) echo "bad luck from Japan";;
  17) echo "bad luck from Italy";;
  esac
  ((contador++))
done