#!/usr/bin/env bash
# This script is displaying numbers to 10 with messages

h=0
m=1


while [ "$h" -le 12 ]; do
	echo "Hour: $h"
	while [ "$m" -le 59 ]; do
		
		echo "$m"
		if [ "$m" -eq 59 ]; then
			m=1
			((h++))
			break
		else
			((m++))
		fi
	done
done